// Main
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_INPUT_FIELD = 'UPDATE_INPUT_FIELD'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

// Login
export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_TOKEN = 'SET_TOKEN'

// Trainee
export const UPDATE_TRAINEE_FIELD = 'UPDATE_TRAINEE_FIELD'
export const SET_TRAINEE_LIST = 'SET_TRAINEE_LIST'
export const REMOVE_TRAINEE = 'REMOVE_TRAINEE'
export const SET_CURRENT_TRAINEE = 'SET_CURRENT_TRAINEE'
export const GET_CURRENT_TRAINEE = 'GET_CURRENT_TRAINEE'
export const SET_TRAINEE_PACKAGE_LIST = 'SET_TRAINEE_PACKAGE_LIST'

// Training Package
export const UPDATE_TRAINING_PACKAGE_FIELD = 'UPDATE_TRAINING_PACKAGE_FIELD'
export const SET_TRAINING_PACKAGE_LIST = 'SET_TRAINING_PACKAGE_LIST'
export const REMOVE_TRAINING_PACKAGE = 'REMOVE_TRAINING_PACKAGE'
export const SET_CURRENT_TRAINING_PACKAGE = 'SET_CURRENT_TRAINING_PACKAGE'

// Goal
export const UPDATE_GOAL_FIELD = 'UPDATE_GOAL_FIELD'
export const SET_GOAL_LIST = 'SET_GOAL_LIST'
export const REMOVE_GOAL = 'REMOVE_GOAL'
export const SET_CURRENT_GOAL = 'SET_CURRENT_GOAL'

// Session
export const UPDATE_SESSION_FIELD = 'UPDATE_SESSION_FIELD'
export const SET_SESSION_LIST = 'SET_SESSION_LIST'
export const REMOVE_SESSION = 'REMOVE_SESSION'
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION'

// Diet
export const UPDATE_DIET_FIELD = 'UPDATE_DIET_FIELD'
export const SET_DIET_LIST = 'SET_DIET_LIST'
export const REMOVE_DIET = 'REMOVE_DIET'
export const SET_CURRENT_DIET = 'SET_CURRENT_DIET'

// Payment
export const UPDATE_PAYMENT_FIELD = 'UPDATE_PAYMENT_FIELD'
export const SET_PAYMENT_LIST = 'SET_PAYMENT_LIST'
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT'
export const SET_CURRENT_PAYMENT = 'SET_CURRENT_PAYMENT'
export const SET_PAYMENT_MAP = 'SET_PAYMENT_MAP'

// TraineeStatus
export const UPDATE_TRAINEE_STATUS_FIELD = 'UPDATE_TRAINEE_STATUS_FIELD'
export const SET_TRAINEE_STATUS_LIST = 'SET_TRAINEE_STATUS_LIST'
export const REMOVE_TRAINEE_STATUS = 'REMOVE_TRAINEE_STATUS'
export const SET_CURRENT_TRAINEE_STATUS = 'SET_CURRENT_TRAINEE_STATUS'

// Exercise
export const UPDATE_EXERCISE_FIELD = 'UPDATE_EXERCISE_FIELD'
export const SET_EXERCISE_LIST = 'SET_EXERCISE_LIST'
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE'

// Scheduled Exercise
export const UPDATE_SCHEDULED_EXERCISE_FIELD = 'UPDATE_SCHEDULED_EXERCISE_FIELD'
export const SET_CURRENT_DAY = 'SET_CURRENT_DAY'
export const SET_SCHEDULED_EXERCISE_LIST = 'SET_SCHEDULED_EXERCISE_LIST'
export const REMOVE_SCHEDULED_EXERCISE = 'REMOVE_SCHEDULED_EXERCISE'
